import type { Metadata } from "next";
import { DataProvider } from "./contexts/DataContext";

export const metadata: Metadata = {
  title: "Products List",
  description: "A starter generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DataProvider>{children}</DataProvider>
      </body>
    </html>
  );
}
